### PR TITLE
Turnoff backend unittest

### PR DESCRIPTION
**Pull request by zephyr-l**
When the issue was fixed, please turn the unit tests back on.

Other triggers can be managed in Console - Cloud Build.

Screen Shot 2020-12-29 at 5 03 01 PM

### CODE REVIEW

**Review by mikzat — CHANGES_REQUESTED** [review]
Could you please undo any style changes? It's extremely difficult to identify what lines changed specifically to turn off the unit tests.

**Comment by zephyr-l** [comment]
I am not quite sure if we just want to deploy this into Master/Prod or we would like to "have the fix" AND "merge Master to Prod". I rebased this from Master and now it should work. Any additional changes should have the yaml file included in their branch so that the test can pass.

**Comment by zephyr-l** [comment]
By the way there are front-end testings failing as well. Shall we just remove all the unit-testing checks or we plan to fix the unit tests first?

**Review by mikzat — APPROVED** [review]

**Comment by mikzat** [comment]
Thanks Zephyr! 

For now we only agreed to disable the backend tests as the frontend ones were ok last time we checked. We should look into fixing FE tests rather than disabling. But thanks to this PR we now know where to look to disable them if we need to.

**Pull request merged**
